INSERT INTO state_table (id, state_code, state_name, population) values (1, 'ap', 'Andhra Pradesh', 49386799);
INSERT INTO state_table (id, state_code, state_name, population) values (2, 'ar', 'Arunachal Pradesh', 	1382611);
INSERT INTO state_table (id, state_code, state_name, population) values (3, 'as', 'Assam', 31169272);
INSERT INTO state_table (id, state_code, state_name, population) values (4, 'br', 'Bihar', 103804637);
INSERT INTO state_table (id, state_code, state_name, population) values (5, 'cg', 'Chhattisgarh', 25540196);
INSERT INTO state_table (id, state_code, state_name, population) values (6, 'ga', 'Goa', 1457723);
INSERT INTO state_table (id, state_code, state_name, population) values (7, 'gj', 'Gujarat', 60383628);
INSERT INTO state_table (id, state_code, state_name, population) values (8, 'hr', 'Haryana', 25353081);
INSERT INTO state_table (id, state_code, state_name, population) values (9, 'hp', 'Himachal Pradesh', 6864602);
INSERT INTO state_table (id, state_code, state_name, population) values (10, 'jh', 'Jharkhand', 32966238);